IF ( ${USE_EXTERNALS} )
IF ( "${EXTERNALS_DIRECTORY}" STREQUAL "" )
    SET ( EXTERNALS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../../svn_HPCC/dev/Third_party"
          CACHE PATH "SVN Third Party Folders" )
ENDIF ()
ENDIF ()

#set ( AGG_ROOT "${EXTERNALS_DIRECTORY}/agg" )
find_package( AGGSRC )
if ( AGGSRC_FOUND )
else ( )
    MESSAGE( "AGG Sources not found:  " ${AGG_ROOT})
endif ( )

set ( EXPAT_ROOT "${EXTERNALS_DIRECTORY}/expat" )
find_package( EXPAT )
if ( EXPAT_FOUND )
else ( )
    MESSAGE( "EXPAT not found:  " ${EXPAT_ROOT})
endif ( )

#set ( FIREBREATHSRC_ROOT "${EXTERNALS_DIRECTORY}/firebreath" )
find_package( FIREBREATHSRC )
if ( FIREBREATHSRC_FOUND )
else ( )
    MESSAGE( "FIREBREATH Sources not found:  " ${FIREBREATHSRC_ROOT})
endif ( )

#set ( GRAPHVIZSRC_ROOT "${EXTERNALS_DIRECTORY}/graphviz2" )
find_package( GRAPHVIZSRC )
if ( GRAPHVIZSRC_FOUND )
else ( )
    MESSAGE( "GRAPHVIZ Sources not found:  " ${GRAPHVIZSRC_ROOT})
endif ( )

IF (WIN32)
set ( WTL_ROOT "${EXTERNALS_DIRECTORY}/wtl" )
find_package( WTL )
if ( WTL_FOUND )
else ( )
    MESSAGE( "WTL libraries were not found:  " ${WTL_ROOT})
endif ( )
endif ( WIN32 )

IF (WIN32)
    SET(Boost_USE_STATIC_LIBS        ON)
    SET(Boost_USE_MULTITHREADED      ON)
    SET(Boost_USE_STATIC_RUNTIME    OFF)
ENDIF (WIN32)
SET( Boost_ADDITIONAL_VERSIONS "1.48" "1.44" "1.43" "1.43.0" "1.42" "1.42.0" )
FIND_PACKAGE( Boost 1.48 COMPONENTS date_time thread graph serialization regex )
IF( Boost_FOUND )
    ADD_DEFINITIONS( -DBOOST_ALL_NO_LIB )
ELSE( Boost_FOUND )
    MESSAGE( "BOOST libraries were not found:  " ${BOOST_ROOT})
ENDIF( Boost_FOUND )

if (WIN32)
    #SET ( FREETYPE_INCLUDE_DIR_freetype2 ${EXTERNALS_DIRECTORY}/freetype2/include )
    #SET ( FREETYPE_INCLUDE_DIR_ft2build ${EXTERNALS_DIRECTORY}/freetype2/include )
    #SET ( FREETYPE_LIBRARY ${EXTERNALS_DIRECTORY}/freetype2/objs/win32/vc2008/freetype239MT.lib )
else (WIN32)
endif (WIN32)
FIND_PACKAGE( Freetype )
IF( FREETYPE_FOUND )
ELSE( FREETYPE_FOUND )
    MESSAGE( "Freetype library was not found" )
ENDIF( FREETYPE_FOUND )

IF (WIN32)
ELSE (WIN32)
    FIND_PACKAGE( Threads )
    IF( THREADS_FOUND )
    ELSE( THREADS_FOUND )
        MESSAGE( "Threads library was not found" )
    ENDIF( THREADS_FOUND )
ENDIF (WIN32)